AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/application.rb'
    - 'db/**/*'
    - 'spec/*_helper.rb'
  TargetRubyVersion: 2.3
Metrics/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Enabled: false
